
name: Automatyczna Aktualizacja Produktów Gmodstore

on:
  
  schedule:
    - cron: '0 8 * * *'
  

  workflow_dispatch:

jobs:
  scrape:
    
    runs-on: ubuntu-latest

    steps:
      
      - name: Pobranie kodu repozytorium
        uses: actions/checkout@v4

      
      - name: Ustawienie Pythona
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      
      - name: Instalacja zależności
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      
      - name: Uruchomienie skryptu scrapującego
        run: python scrape_products.py

      
      - name: Zapisanie zmian w pliku products.json
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          
          commit_message: '🤖 Automatyczna aktualizacja listy produktów'
        
          file_pattern: 'products.json'